dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
  homebrew:
    update: true
    packages:
      - python

install: 
  - python3 -m pip install -e .[dev]

script:
  - make lint
  - make test

after_success:
    - codecov --token 3d500dbc-ad4f-4aa4-9f26-2616b0d75569

branches:
  only:
  - master

notifications:
  email: false
